### ISSUE TITLE
where is the keyboard

### ISSUE THREAD

**Issue by rahul107** [bhavita/CustomKeyboard#1]
after run your project and install app in my phone i see that there is no keyboard only "hello world" is showing the activity

**Comment by bhavita** [comment]
The way keyboard in android works is you have to enable the keyboard. 

The "hello world" is just a base activity to showcase the settings or other options for the keyboard.
To set the keyboard, first go in your device Settings->Language&Inputs and then depending on your device, there will be an option to enable the keyboard. 
Finally, go in your current keyboard settings and set this 'MyKeyboard' as your default keyboard.

**Comment by rahul107** [comment]
ok i will check
