### ISSUE TITLE
Query 

### ISSUE THREAD

**Issue by envyvy** [bhavita/CustomKeyboard#2]
.

**Comment by bhavita** [comment]
What help do you require?

**Comment by envyvy** [comment]
Thanks for your reply. I am planning to build an Indic keyboard app based on the design I have thought. I want to start with the devanaagri inscript keyboard and then modify for other Indic scripts. Android is what I want to start with and will move to other platforms if this becomes any successful. I am not a programmer and have never worked on android. I am looking for a guru who can guide me how to begin and get going so that I can successfully design it as soon as possible. Your profile says that you are an expert on this, so nothing better than this to get guidance from you. Cheers, Vikas
